### ISSUE TITLE
Auto Save

### ISSUE THREAD

**Issue by jacob-shuman** [jerryshueh/simple-noter#12]
Hi @jerryshueh I believe that auto save functionality would be great for your app!
I'm up to implement that functionality into the project if it's ok with you?

**Comment by jerryshueh** [comment]
Jacob, that is a great idea. I had originally implemented autosave on a 3 second timer, but replaced it with the manual save. However, I think it will be worth it to bring autosaving back, and perhaps allow the user to set the frequency of the save. You have my "go ahead" to implement this feature!

**Comment by jacob-shuman** [comment]
That’s awesome, I’ll get right on it!

Thank you for the prompt response!

**Comment by jerryshueh** [comment]
Feature has been added to address this issue, so this is now considered closed.
