### ISSUE TITLE
The default message could be on placeholder.

### ISSUE THREAD

**Issue by Reza-Rajabi** [jerryshueh/simple-noter#2]
The default message: "Nothing is saved yet, so just type here!" could be on a placeholder so that, the user doesn't need to delete it.

**Comment by jerryshueh** [comment]
This issue has been resolved and the functionality for default message has been added. Thanks to Reza-Rajabi for taking the time to improve this application!

**Comment by Reza-Rajabi** [comment]
Thank you.
